### ISSUE TITLE
Selection example not up-to-date

### ISSUE THREAD

**Issue by MarcBuch** [erikgeiser/promptkit#14]
## What?

The example code for the selection is not working anymore. `selection.New()` now takes a `[]*selection.Choice` instead of the displayed `[]string`.

## Fix

I would suggest adjusting the selector example to:

```go
choices := selection.Choices([]string{"Horse", "Car", "Plane", "Bike"})
sp := selection.New("What do you pick?", choices)

// ...
```

Thanks to you for creating this repo! It is very easy to use and opens the world for newbies to bubble tea. If needed, I can quickly create a PR.

**Comment by erikgeiser** [comment]
I have now tagged and released a new version which fixes the mismatch between documentation and latest released version.
