### ISSUE TITLE
LAtest bubbles break promptkit

### ISSUE THREAD

**Issue by jlec** [erikgeiser/promptkit#22]
https://github.com/charmbracelet/bubbles/pull/341 leads to

```
➜  go run main.go
# github.com/erikgeiser/promptkit/selection
../../../go/pkg/mod/github.com/erikgeiser/promptkit@v0.8.0/selection/model.go:144:14: filterInput.BackgroundStyle undefined (type textinput.Model has no field or method BackgroundStyle)
```

**Comment by erikgeiser** [comment]
They made a breaking change, but I recently bumped all dependencies and I think I already fixed it. Could you try the current main branch of promptkit? I have not tagged a new release yet.

**Comment by jlec** [comment]
Looks good. Not problem at HEAD.

**Comment by erikgeiser** [comment]
Great, I'll close this issue after I tag a release tomorrow.

**Comment by avamsi** [comment]
@erikgeiser any chance you could tag that release? Thanks!

**Comment by erikgeiser** [comment]
Sorry, I completely forgot about it. Thanks for reminding me. [Here it is.](https://github.com/erikgeiser/promptkit/releases/tag/v0.9.0)
